### ISSUE TITLE
是否可以直接OSCNet训练好的模型消除其他图像的金属伪影

### ISSUE THREAD

**Issue by TianSong1991** [hongwang01/OSCNet#2]
我是一个对图像处理感兴趣的研究者，最近了解到您的OSCNet项目，我对您的工作表示赞赏，这是一项出色的工作。
我最近遇到了一个问题，我希望能够使用您的OSCNet模型来消除图像中的金属伪影。我想请问您是否已经训练了一个用于消除金属伪影的模型，或者是否可以使用您的模型来处理其他图像中的金属伪影。
非常感谢您的时间和关注，期待您的回复。

**Comment by hongwang01** [comment]
> 我是一个对图像处理感兴趣的研究者，最近了解到您的OSCNet项目，我对您的工作表示赞赏，这是一项出色的工作。 我最近遇到了一个问题，我希望能够使用您的OSCNet模型来消除图像中的金属伪影。我想请问您是否已经训练了一个用于消除金属伪影的模型，或者是否可以使用您的模型来处理其他图像中的金属伪影。 非常感谢您的时间和关注，期待您的回复。

欢迎对我们工作的关注。对于OSCNet及OSCNet+, 本仓库均已开源训练好的模型，可以按照readme中的测试code说明进行同域/跨域测试即可。https://github.com/hongwang01/OSCNet/tree/main/pretrained_model

**Comment by TianSong1991** [comment]
@hongwang01 您好，我clone您的代码，并且根据您OSCNet的readme中Testing测试了OSCNet和OSCNet+，在test.py里面只循环了一次就报错，提示我没有1.h5文件，我看了看github上也没有这个文件，请问需要继续下载.h5文件吗？
![1](https://github.com/hongwang01/OSCNet/assets/33627940/d8ee345a-f7c8-4d25-8e2c-3dba20b07f01)
同时测试了OSCNet和OSCNet+都出现上述问题，另外，如果我要测试我自己的金属伪影数据，我应该如何修改让模式去测试我自己的数据并生成结果，谢谢。

**Comment by hongwang01** [comment]
> @hongwang01 您好，我clone您的代码，并且根据您OSCNet的readme中Testing测试了OSCNet和OSCNet+，在test.py里面只循环了一次就报错，提示我没有1.h5文件，我看了看github上也没有这个文件，请问需要继续下载.h5文件吗？ ![1](https://private-user-images.githubusercontent.com/33627940/345674347-d8ee345a-f7c8-4d25-8e2c-3dba20b07f01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNTk2MDksIm5iZiI6MTcyMDA1OTMwOSwicGF0aCI6Ii8zMzYyNzk0MC8zNDU2NzQzNDctZDhlZTM0NWEtZjdjOC00ZDI1LThlMmMtM2RiYTIwYjA3ZjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDAyMTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNzMzZWI0NWZkOWE2MTdiNWJkOWQxNjNlOWRiOGQyZDI5ZTJhNjE1YjNhZDgxY2QyNTQ1ZTQyOGRlZjAxOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJyMEEr8HZe4w85tN2XO5tUo4XLXBDg954JS3UTCAsA) 同时测试了OSCNet和OSCNet+都出现上述问题，另外，如果我要测试我自己的金属伪影数据，我应该如何修改让模式去测试我自己的数据并生成结果，谢谢。

请仔细阅读我们的readme，仓库里只是提供了demo data，你没按readme下载完整data自然会报错。如果要测试你自己的数据，你需要做的是根据你自己的数据路径修改读入方式，然后按照我们模型需要的数据预处理方式操作并加载我们公开的推理模型进行测试即可。

**Comment by TianSong1991** [comment]
@hongwang01 好的，多谢提醒。

**Comment by Chan-Developer** [comment]
你好，请问模型需要的数据预处理方式是什么样呢，我需要怎么处理自己的数据集才能使用您的模型呢，谢谢

**Comment by ZHOUAmara** [comment]
@CHENLIANG456 你好，我最近也在研究这个算法，请问你找到测试的预处理方法了吗？急需您的帮助。

**Comment by hongwang01** [comment]
> @CHENLIANG456 你好，我最近也在研究这个算法，请问你找到测试的预处理方法了吗？急需您的帮助。

谢谢对我们工作关注，我们在这里已经给了回复，
https://github.com/hongwang01/OSCNet/issues/3

**Comment by ZHOUAmara** [comment]
> > @CHENLIANG456 你好，我最近也在研究这个算法，请问你找到测试的预处理方法了吗？急需您的帮助。
> 
> 谢谢对我们工作关注，我们在这里已经给了回复， #3

其实我想问的是，如果我用自己的数据集来测试，那么我是只有一幅含金属假体伪影的CT切片，我该怎么调用模型，因为其余三种图像获取方式文章和代码里我都没看到详细介绍

**Comment by hongwang01** [comment]
> > > @CHENLIANG456 你好，我最近也在研究这个算法，请问你找到测试的预处理方法了吗？急需您的帮助。
> > 
> > 
> > 谢谢对我们工作关注，我们在这里已经给了回复， #3
> 
> 其实我想问的是，如果我用自己的数据集来测试，那么我是只有一幅含金属假体伪影的CT切片，我该怎么调用模型，因为其余三种图像获取方式文章和代码里我都没看到详细介绍

理解。针对你的数据场景，处理方式参考这里：https://github.com/hongwang01/InDuDoNet/blob/main/CLINIC_metal/preprocess_clinic/preprocessing_clinic.py
这个issue已经closed了，如还有问题，可以在这里继续跟进。https://github.com/hongwang01/OSCNet/issues/3#issuecomment-2398723257

同时感谢你的问题，近期我们会在本repo中给以更新说明。

**Comment by ZHOUAmara** [comment]
> > 其实我想问的是，如果我用自己的数据集来测试，那么我是只有一幅含金属假体伪影的CT切片，我该怎么调用模型，因为其余三种图像获取方式文章和代码里我都没看到详细介绍
> 
> 理解。针对你的数据场景，处理方式参考这里：https://github.com/hongwang01/InDuDoNet/blob/main/CLINIC_metal/preprocess_clinic/preprocessing_clinic.py 这个issue已经closed了，如还有问题，可以在这里继续跟进。[#3 (comment)](https://github.com/hongwang01/OSCNet/issues/3#issuecomment-2398723257)
> 
> 同时感谢你的问题，近期我们会在本repo中给以更新说明。

好的非常感谢您
